repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "--with", "dev", "-o", "requirements.txt" ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.249'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        types: [ "python" ]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.0.1'
#    hooks:
#      - id: mypy
#        args: ["src"]
